pengovbr/mod-sei-pen

Makefile, docs/INSTALL.md, docs/changelogs/CHANGELOG-2.1.4.md, src/PENIntegracao.php, src/rn/AssinaturaHashRN.php, src/rn/Editor3011RN.php, src/rn/ExpedirProcedimentoRN.php, src/rn/VerificadorInstalacaoRN.php, src/scripts/sei_atualizar_versao_modulo_pen.php, src/scripts/sip_atualizar_versao_modulo_pen.php, tests/funcional/assets/config/ConfiguracaoModPEN.php, tests/funcional/tests/TramiteProcessoComDevolucaoAlteracaoURLTest.php
E adiciona logicas no Makefile para facilitar a subida dos ambientes
=> Implementa lógica para manter hash ao modificar URLs dos órgãos

src/pen_parametros_configuracao.php
Evolução da página de configurações do módulo, foi ajustado o filtro de tipos de processos e a criação dos tooltips.
=> Ajuste da página de parâmentros

Makefile, docs/changelogs/CHANGELOG-3.1.3.md, src/PENIntegracao.php, src/css/pen_procedimento_expedir_sei402.css, src/int/ProcessoEletronicoINT.php, src/js/expedir_processo/pen_procedimento_expedir.js, src/pen_expedir_lote.php, src/pen_procedimento_expedir.php, src/rn/AssinaturaHashRN.php, src/rn/EditorSEI4RN.php, src/rn/ExpedirProcedimentoRN.php, src/rn/VerificadorInstalacaoRN.php, src/scripts/sei_atualizar_versao_modulo_pen.php, src/scripts/sip_atualizar_versao_modulo_pen.php, tests/funcional/src_sei4/paginas/PaginaProcesso.php
ajustes necessários para compatibilidade.
=> Compatibilidade SEI 4.0.3

src/rn/AssinaturaHashRN.php, src/rn/Editor3011RN.php, src/rn/EditorSEI4RN.php, src/rn/ExpedirProcedimentoRN.php
Devido alterações no SEI4, a tarja de assinatura estava causando erros de hash nos trâmites
Closes #130
=> Altera modo de criação de tarja de assinatura

docs/changelogs/CHANGELOG-3.1.10.md, src/PENIntegracao.php, src/scripts/sei_atualizar_versao_modulo_pen.php, src/scripts/sip_atualizar_versao_modulo_pen.php
Correção de erro no carregamento da página de Controle de Processos
Closes #139
=> Correção de erro no carregamento da página de Controle de Processos

Makefile, src/rn/ExpedirProcedimentoRN.php, tests_sei3/funcional/phpunit.xml, tests_sei4/funcional/phpunit.xml, tests_sei4/funcional/tests/TramiteProcessoComHistoricoTest.php
Procura por id_procedimento ou id_procedimento_anexado conforme se o documento está em processo anexado ou não
Closes #162
=> fix: busca espécie documental

src/rn/ExpedirProcedimentoRN.php
fix: Correção de erro na geração de hash ao mudar a sigla do órgão
closes #183
=> fix: Correção de erro na geração de hash ao mudar a sigla do órgão

src/rn/VerificadorInstalacaoRN.php, src/scripts/verifica_instalacao_modulo_pen.php
Melhorando o script de instalação do módulo pen.
=> feat: Melhoria no script de instalação do módulo pen

src/rn/PendenciasTramiteRN.php, src/rn/ProcessoEletronicoRN.php, src/rn/VerificadorInstalacaoRN.php
closes ([#188](https://github.com/supergovbr/mod-sei-pen/issues/188))
=> feat: Adicionar verificação na chamada da constante CURLOPT_SSL_VERIFYHOST

src/rn/Editor3011RN.php, src/rn/EditorSEI4RN.php, src/rn/ExpedirProcedimentoRN.php
Foi alterado no órgão e essa alteração altera o HASH no envio. Foi pensado que poderia ter sido feita alteração somente como sigla do órgão mas já existe documentos enviados com a sigla SUPER.
=> WIP: fix: adiciona checagem se a sigla do sistema foi alterada para SUPER

Makefile
Corrige a issue 218 que apareceu após o merge do dia 07/02.
Closes #218
=> Correção da issue 218

tests_super/funcional/src/paginas/PaginaIniciarProcesso.php, tests_super/funcional/src/paginas/PaginaProcesso.php, tests_super/funcional/src/paginas/PaginaTeste.php, tests_super/funcional/tests/TramiteProcessoComCancelamentoTest.php
Corrigir tags para que o testes funcionais se adaptem a estrutura do SUPER
=> feat: Adaptar testes funcionais para SUPER

src/rn/ProcessoEletronicoRN.php, src/rn/VerificadorInstalacaoRN.php
=> chore: adiciona LOGs para a verificação de conexão

jenkins/01-Simples.groovy, jenkins/02-TodasBases.groovy, jenkins/03-TodasVersoes.groovy
Ajustes nos jobs jenkins para contemplar as ultimas evolucoes do modulos. Agora o job roda testes no sei e super
=> Ajustes nos jobs jenkins

src/rn/ReceberProcedimentoRN.php
=> feat: Correção de recusa por motivo: Documento não foi recebido pela unidade atual

src/dto/PenMapTipoProcedimentoDTO.php, src/pen_map_orgaos_mapeamento_tipo_listar.php, src/pen_map_tipo_processo_reativar.php, src/rn/PenParametroRN.php, src/scripts/sip_atualizar_versao_modulo_pen.php
=> feat: corrçeão de encode de arquivos

src/bd/PenMetaBD.php, src/rn/ProcessoExpedidoRN.php, src/rn/ReceberProcedimentoRN.php, src/scripts/sei_atualizar_versao_modulo_pen.php, src/scripts/sip_atualizar_versao_modulo_pen.php, tests_sei4/funcional/env_postgresql, tests_sei4/funcional/tests/CenarioBaseTestCase.php, tests_super/funcional/env_postgresql, tests_super/funcional/tests/CenarioBaseTestCase.php
adiciona env_postgresql (sei4, seioficial) e modificações sugeridas na issue 366.
closes #395
=> feat: adiciona compatibilidade com postgresql no sei4 e sei oficial

src/PENIntegracao.php, src/pen_map_hipotese_legal_envio_listar.php, src/pen_map_hipotese_legal_recebimento_listar.php, src/pen_map_unidade_listar.php, src/scripts/sip_atualizar_versao_modulo_pen.php
Abertura de PR para correção da nomenclatura do modulo PEN para a release versão 3.6.0 conforme revisão (issue #236 )
=> refactor: alterar nome do menu processo eletrônico nacional para tramita gov.br para release 360

src/PENIntegracao.php
Abertura de PR para reversão da nomenclatura do modulo conforme revisão (issue https://github.com/pengovbr/mod-sei-pen/issues/236 )
=> refactor: revertendo valor de constante 

src/rn/ProcessoEletronicoRN.php
limpeza de código que não é mais utilizado pois mensagem da API foi alterada.
closes #481
=> cleanup: remover codigo que tratava mensagem da API

src/int/ProcessoEletronicoINT.php, src/pen_expedir_lote.php, src/rn/PenExpedirLoteRN.php
=> feat: melhoria de mensagem para envio com sucesso de tramite em bloco

src/rn/ProcessoEletronicoRN.php, src/scripts/sei_atualizar_versao_modulo_pen.php, tests_sei4/funcional/src/paginas/PaginaPenHipoteseLegalListar.php, tests_sei4/funcional/tests/CenarioBaseTestCase.php, tests_sei4/funcional/tests/MapeamentoHipoteseLegalTest.php, tests_sei41/funcional/src/paginas/PaginaPenHipoteseLegalListar.php, tests_sei41/funcional/tests/CenarioBaseTestCase.php, tests_sei41/funcional/tests/MapeamentoHipoteseLegalTest.php, tests_super/funcional/src/paginas/PaginaPenHipoteseLegalListar.php, tests_super/funcional/tests/CenarioBaseTestCase.php, tests_super/funcional/tests/MapeamentoHipoteseLegalTest.php
=> feat: mapeamento automatico de hipoteses legais

src/PENIntegracao.php, src/rn/PenHipoteseLegalRN.php
=> 348 criar críticas para impedir desativar ou excluir tipos de hipoteses legais

src/PENIntegracao.php, src/pen_expedir_bloco.php, src/rn/ProcessoEletronicoRN.php
Correção de busca de unidades para tramite mapeadas no organograma e envio em bloco.
=> fix: correção de organograma e envio em bloco

src/pen_expedir_bloco.php, src/pen_map_envio_parcial_cadastrar.php, src/pen_map_restricao_envio_comp_digitais_cadastrar.php, src/pen_procedimento_expedir.php
- Ocultar o botão do organograma da tela de envio do processo, 
- Envio de processo em bloco, 
- Mapeamento de envio parcial,
- Restrição de componentes digitais
=> 540 ocultar botao organograma

src/scripts/sip_atualizar_versao_modulo_pen.php
=> fix: alteracao acesso menu tramita.gov.br para perfil basico

src/scripts/sip_atualizar_versao_modulo_pen.php
=> fix: adicionar recurso 'pen_expedir_bloco' para perfil basico

src/scripts/sei_atualizar_versao_modulo_pen.php
=> feat: alteração de nome de bloco generico e criação somente quando existe processos legados

tests_sei4/funcional/tests/TramiteBlocoExternoLimiteAnexoTest.php, tests_sei4/funcional/tests/TramiteBlocoExternoLimiteTest.php, tests_super/funcional/tests/TramiteBlocoExternoLimiteAnexoTest.php, tests_super/funcional/tests/TramiteBlocoExternoLimiteTest.php
=> Refatoração de testes

tests_sei4/funcional/src/fixtures/PenMapUnidadesRestricaoFixture.php, tests_sei4/funcional/tests/MapeamentoDeUnidadesComLimitacaoDeRepositoriosTest.php, tests_sei41/funcional/src/fixtures/PenMapUnidadesRestricaoFixture.php, tests_sei41/funcional/tests/MapeamentoDeUnidadesComLimitacaoDeRepositoriosTest.php, tests_super/funcional/src/fixtures/PenMapUnidadesRestricaoFixture.php, tests_super/funcional/tests/MapeamentoDeUnidadesComLimitacaoDeRepositoriosTest.php
=> test: renomear teste e efetuar limpeza antes e pos execucao

src/scripts/sei_atualizar_versao_modulo_pen.php
criação de bloco generico com atualização de versão
Closes #506
=> fix: criação de bloco generico com atualização de versão

tests_sei4/funcional/src/fixtures/BlocoDeTramiteFixture.php, tests_sei4/funcional/tests/RecebimentoRecusaJustificativaGrandeTest.php, tests_sei4/funcional/tests/TramiteBlocoExternoProcessoJaIncluidoEmBlocoTest.php, tests_sei41/funcional/src/fixtures/BlocoDeTramiteFixture.php, tests_sei41/funcional/tests/RecebimentoRecusaJustificativaGrandeTest.php, tests_sei41/funcional/tests/TramiteBlocoExternoLimiteAnexoTest.php, tests_sei41/funcional/tests/TramiteBlocoExternoLimiteTest.php, tests_sei41/funcional/tests/TramiteBlocoExternoProcessoJaIncluidoEmBlocoTest.php, tests_sei41/funcional/tests/TramiteProcessoComDevolucaoContendoOutroAnexadoTest.php, tests_sei41/funcional/tests/TramiteProcessoContendoDocumentoCanceladoTest.php, tests_sei41/funcional/tests/TramiteProcessoContendoDocumentoExternoTest.php, tests_sei41/funcional/tests/TramiteRecebimentoDocumentoAnexadoTest.php, tests_super/funcional/src/fixtures/BlocoDeTramiteFixture.php, tests_super/funcional/tests/RecebimentoRecusaJustificativaGrandeTest.php, tests_super/funcional/tests/TramiteBlocoExternoProcessoJaIncluidoEmBlocoTest.php
Closes #559 
Tambem tem adicionado refatoração de testes pendentes no SEI 4.1.1 das issues #490 e #525
=> 559 refatoracao de testes

src/PENIntegracao.php, src/pen_map_unidade_listar.php
- Correção de mapeamento somente de repoisitorios par alistar unidades; 
- Alteração do titulo da página de listar "Mapeamento de Unidades" para "Mapeamento de Unidades";
Closes: #196
=> fix: correção de limitação de repositorio/unidades

tests_sei4/funcional/tests/MapeamentoTipoProcessoDesativarReativarTest.php, tests_sei41/funcional/tests/MapeamentoTipoProcessoDesativarReativarTest.php, tests_sei41/funcional/tests/MapeamentoTipoProcessoExcluirTest.php
Closes #559 
Correções de algumas refatorações de testes
=> feat: correcao de refatoracoes de alguns testes

src/scripts/sei_atualizar_versao_modulo_pen.php
=> feat: criar um bloco pra cada unidade que tenha processos em lote

src/scripts/sei_atualizar_versao_modulo_pen.php
=> 527 erro ao atualizar modulo para versao 3.6.2

src/pen_tramita_em_bloco_protocolo_listar.php, src/pen_tramite_processo_em_bloco_cadastrar.php, src/rn/PenBlocoProcessoRN.php, src/scripts/sei_atualizar_versao_modulo_pen.php
- Corrigir exclusão de arquivos cancelados/recusados ao selecionados juntos com processos concluidos
- Corrigir escript de atualização para trazer o status correto dos processos na versão 3.6.2
- Corrigir validação ao tentar inserir processos que não podem ser anexados no bloco
=> fix: corrigir exclusão de processos em bloco parcial e script de atualização

src/rn/ExpedirProcedimentoRN.php
Documento precisa estar cancelado sem assinatura e criado em outra unidade
=> fix: processo com documento cancelado no 3.1.7

tests_sei4/funcional/tests/FixtureCenarioBaseTestCase.php, tests_sei4/funcional/tests/TramiteProcessoComCancelamentoTest.php, tests_sei4/funcional/tests/TramiteProcessoComDevolucaoAlteracaoURLTest.php, tests_sei4/funcional/tests/TramiteProcessoComDevolucaoTest.php, tests_sei4/funcional/tests/TramiteProcessoComDevolucaoUnidadeDiferenteTest.php, tests_sei4/funcional/tests/TramiteProcessoComDocumentoRestritoHipotesePadraoTest.php, tests_sei4/funcional/tests/TramiteProcessoComHistoricoTest.php, tests_sei4/funcional/tests/TramiteProcessoContendoDocumentoCanceladoSemTamanhoTest.php, tests_sei41/funcional/tests/FixtureCenarioBaseTestCase.php, tests_sei41/funcional/tests/TramiteProcessoComCancelamentoTest.php, tests_sei41/funcional/tests/TramiteProcessoComDevolucaoAlteracaoURLTest.php, tests_sei41/funcional/tests/TramiteProcessoComDevolucaoTest.php, tests_sei41/funcional/tests/TramiteProcessoComDevolucaoUnidadeDiferenteTest.php, tests_sei41/funcional/tests/TramiteProcessoComDocumentoRestritoHipotesePadraoTest.php, tests_sei41/funcional/tests/TramiteProcessoComHistoricoTest.php, tests_sei41/funcional/tests/TramiteProcessoContendoDocumentoCanceladoSemTamanhoTest.php, tests_super/funcional/tests/FixtureCenarioBaseTestCase.php, tests_super/funcional/tests/TramiteProcessoComCancelamentoTest.php, tests_super/funcional/tests/TramiteProcessoComDevolucaoAlteracaoURLTest.php, tests_super/funcional/tests/TramiteProcessoComDevolucaoTest.php, tests_super/funcional/tests/TramiteProcessoComDevolucaoUnidadeDiferenteTest.php, tests_super/funcional/tests/TramiteProcessoComDocumentoRestritoHipotesePadraoTest.php, tests_super/funcional/tests/TramiteProcessoComHistoricoTest.php, tests_super/funcional/tests/TramiteProcessoContendoDocumentoCanceladoSemTamanhoTest.php
=> 560 refatoracao de testes

tests_sei4/funcional/tests/FixtureCenarioBaseTestCase.php, tests_sei4/funcional/tests/TramiteProcessoContendoDocumentoMovidoTest.php, tests_sei4/funcional/tests/TramiteProcessoContendoVariosDocumentosTest.php, tests_sei4/funcional/tests/TramiteProcessoDocumentoNaoMapeadoDestinoTest.php, tests_sei4/funcional/tests/TramiteProcessoDocumentoNaoMapeadoOrigemTest.php, tests_sei4/funcional/tests/TramiteProcessoExtensaoNaoMapeadoDestinoTest.php, tests_sei41/funcional/tests/FixtureCenarioBaseTestCase.php, tests_sei41/funcional/tests/TramiteProcessoContendoDocumentoMovidoTest.php, tests_sei41/funcional/tests/TramiteProcessoContendoVariosDocumentosTest.php, tests_sei41/funcional/tests/TramiteProcessoDocumentoNaoMapeadoDestinoTest.php, tests_sei41/funcional/tests/TramiteProcessoDocumentoNaoMapeadoOrigemTest.php, tests_sei41/funcional/tests/TramiteProcessoExtensaoNaoMapeadoDestinoTest.php, tests_super/funcional/tests/CenarioBaseTestCase.php, tests_super/funcional/tests/FixtureCenarioBaseTestCase.php, tests_super/funcional/tests/TramiteProcessoContendoDocumentoMovidoTest.php, tests_super/funcional/tests/TramiteProcessoContendoVariosDocumentosTest.php, tests_super/funcional/tests/TramiteProcessoDocumentoNaoMapeadoDestinoTest.php, tests_super/funcional/tests/TramiteProcessoDocumentoNaoMapeadoOrigemTest.php, tests_super/funcional/tests/TramiteProcessoExtensaoNaoMapeadoDestinoTest.php, tests_super/funcional/tests/TramiteProcessoGestorNaoResponsavelPelaUnidadeMapeadaTest.php
=> 555 refatoracao de testes

tests_sei4/funcional/tests/FixtureCenarioBaseTestCase.php, tests_sei4/funcional/tests/TramiteProcessoRestritoHipotesePadraoTest.php, tests_sei4/funcional/tests/TramiteProcessoRestritoTest.php, tests_sei4/funcional/tests/TramiteProcessoTamanhoAcimaLimiteDestinoTest.php, tests_sei4/funcional/tests/TramiteProcessoUnidadeSemHierarquiaPaiTest.php, tests_sei4/funcional/tests/TramiteProcessosComDevolucaoAmbosAnexadosTest.php, tests_sei4/funcional/tests/TramiteProcessosComDevolucoesEAnexacoesTest.php, tests_sei41/funcional/tests/FixtureCenarioBaseTestCase.php, tests_sei41/funcional/tests/TramiteProcessoRestritoHipotesePadraoTest.php, tests_sei41/funcional/tests/TramiteProcessoRestritoTest.php, tests_sei41/funcional/tests/TramiteProcessoTamanhoAcimaLimiteDestinoTest.php, tests_sei41/funcional/tests/TramiteProcessoUnidadeSemHierarquiaPaiTest.php, tests_sei41/funcional/tests/TramiteProcessosComDevolucaoAmbosAnexadosTest.php, tests_sei41/funcional/tests/TramiteProcessosComDevolucoesEAnexacoesTest.php, tests_super/funcional/tests/FixtureCenarioBaseTestCase.php, tests_super/funcional/tests/TramiteProcessoRestritoHipotesePadraoTest.php, tests_super/funcional/tests/TramiteProcessoRestritoTest.php, tests_super/funcional/tests/TramiteProcessoTamanhoAcimaLimiteDestinoTest.php, tests_super/funcional/tests/TramiteProcessoUnidadeSemHierarquiaPaiTest.php, tests_super/funcional/tests/TramiteProcessosComDevolucaoAmbosAnexadosTest.php, tests_super/funcional/tests/TramiteProcessosComDevolucoesEAnexacoesTest.php
closes #556
depende do PR para o SEI [384](https://github.com/pengovbr/sei/pull/384)
=> tests: refatoracao testes funcionais

src/rn/PenBlocoProcessoRN.php
=> chore: permitir inclusão de processos concluídos dos blocos em processamento

tests_sei4/funcional/tests/TramiteRecebimentoDocumentoAvulsoTest.php, tests_sei41/funcional/tests/TramiteRecebimentoDocumentoAvulsoTest.php, tests_super/funcional/tests/TramiteRecebimentoDocumentoAvulsoTest.php
=> feat: refatoracao de testes utilizando fixtures e dtos

src/scripts/sei_atualizar_versao_modulo_pen.php
=> 600 correcoes nos testes automatizados oracle

tests_super/funcional/tests/TramiteProcessoComDevolucaoAnexadoOutroTest.php, tests_super/funcional/tests/TramiteProcessoComDevolucaoContendoOutroAnexadoTest.php, tests_super/funcional/tests/TramiteRecebimentoDocumentoAvulsoTest.php
=> test: correção de testes funcionais

src/pen_tramita_em_bloco_protocolo_listar.php, src/scripts/sei_atualizar_versao_modulo_pen.php, tests_sei4/funcional/tests/TramiteProcessoComDevolucaoAnexadoOutroTest.php, tests_sei4/funcional/tests/TramiteProcessoComDevolucaoContendoOutroAnexadoTest.php, tests_sei4/funcional/tests/TramiteRecebimentoDocumentoAvulsoTest.php, tests_sei41/funcional/tests/TramiteProcessoComDevolucaoAnexadoOutroTest.php, tests_sei41/funcional/tests/TramiteProcessoComDevolucaoContendoOutroAnexadoTest.php, tests_sei41/funcional/tests/TramiteRecebimentoDocumentoAvulsoTest.php, tests_super/funcional/tests/TramiteProcessoComDevolucaoAnexadoOutroTest.php, tests_super/funcional/tests/TramiteProcessoComDevolucaoContendoOutroAnexadoTest.php, tests_super/funcional/tests/TramiteRecebimentoDocumentoAvulsoTest.php
=> test: correção testes funcionais

src/scripts/sei_atualizar_versao_modulo_pen.php
=> fix: corrige PR 609

src/PENIntegracao.php, src/pen_tramite_bloco_listar.php, src/rn/TramiteEmBlocoRN.php
=> fix: icone "tramite externo" sendo exibido mesmo sem mapeamento de unidade

src/rn/ExpedirProcedimentoRN.php
=> feat: removido recontagem de bolMultiplosComponentes

tests_sei4/funcional/tests/TramiteBlocoExternoLimiteTest.php, tests_sei41/funcional/tests/TramiteBlocoExternoLimiteTest.php, tests_super/funcional/tests/TramiteBlocoExternoLimiteTest.php
=> fix: tratativa de asset de status de bloco quando possui varios processos

tests_sei4/funcional/tests/TramiteEnvioParcialTest.php, tests_sei41/funcional/tests/TramiteEnvioParcialTest.php, tests_super/funcional/tests/TramiteEnvioParcialTest.php
=> test: adicionando fixture em cadastro doc TramiteEnvioParcial

tests_sei4/funcional/tests/TramiteRecebimentoMultiplosComponentesDigitais.php, tests_sei4/funcional/tests/TramiteRecebimentoMultiplosComponentesDigitaisApenasPendentes.php, tests_sei41/funcional/tests/TramiteRecebimentoMultiplosComponentesDigitais.php, tests_sei41/funcional/tests/TramiteRecebimentoMultiplosComponentesDigitaisApenasPendentes.php, tests_super/funcional/tests/TramiteRecebimentoMultiplosComponentesDigitais.php, tests_super/funcional/tests/TramiteRecebimentoMultiplosComponentesDigitaisApenasPendentes.php
=> test: review testes componentes digitais

src/pen_procedimento_cancelar_expedir.php, src/pen_tramita_em_bloco_protocolo_listar.php, src/pen_tramite_bloco_listar.php, src/pen_tramite_processo_em_bloco_cadastrar.php, src/rn/ExpedirProcedimentoRN.php, src/rn/PenBlocoProcessoRN.php, src/rn/ProcessarPendenciasRN.php, src/rn/ReceberProcedimentoRN.php, src/rn/ReceberReciboTramiteRN.php, src/rn/TramitaEmBlocoProtocoloRN.php, src/scripts/sei_atualizar_versao_modulo_pen.php
=> 629 incluir validacoes para processo incluido em bloco unico

src/rn/ReceberProcedimentoRN.php, src/rn/ReceberReciboTramiteRN.php, src/scripts/sei_atualizar_versao_modulo_pen.php
=> feat: cenario de unidade geradora com processo sem andamento aberto

src/pen_tramite_processo_em_bloco_cadastrar.php, src/rn/ExpedirProcedimentoRN.php
Validação para envio de tramite individual incluido em bloco;
Validação para incluir processos em bloco em visualização detalhada.
=> feat: validação de tamite com processo incluido e bloco, validação para visualização detalhada

src/pen_procedimento_expedir_validar.php, src/pen_tramite_processo_em_bloco_cadastrar.php, src/rn/ExpedirProcedimentoRN.php
Validação de envio individual de tramite incluido em bloco validando em envio por bloco
=> 356 corrigir erro ao tentar incluir processos em bloco

tests_sei4/funcional/src/fixtures/BlocoDeTramiteFixture.php, tests_sei4/funcional/tests/TramiteBlocoExternoProcessoJaIncluidoEmBlocoTest.php, tests_sei41/funcional/src/fixtures/BlocoDeTramiteFixture.php, tests_sei41/funcional/tests/TramiteBlocoExternoProcessoJaIncluidoEmBlocoTest.php, tests_super/funcional/src/fixtures/BlocoDeTramiteFixture.php, tests_super/funcional/tests/TramiteBlocoExternoProcessoJaIncluidoEmBlocoTest.php
correção para teste de bloco já incluído com nome da unidade
=> fix: correção para teste de bloco já incluido com nome da unidade

tests_sei4/funcional/tests/FixtureCenarioBaseTestCase.php, tests_sei4/funcional/tests/TramiteBlocoExternoComProcessoNaoMapeadoRecusaTest.php, tests_sei4/funcional/tests/TramiteBlocoExternoInclusaoDeProcessoEmBlocoComHipoteseLegalNaoMapeadaTest.php, tests_sei4/funcional/tests/TramiteProcessoBlocoDeTramiteRegrasTest.php, tests_sei4/funcional/tests/TramiteProcessoComDocumentoRestritoHipotesePadraoTest.php, tests_sei4/funcional/tests/TramiteProcessoComDocumentoRestritoTest.php, tests_sei41/funcional/src/paginas/PaginaTramitarProcesso.php, tests_sei41/funcional/tests/FixtureCenarioBaseTestCase.php, tests_sei41/funcional/tests/TramiteBlocoExternoComProcessoNaoMapeadoRecusaTest.php, tests_sei41/funcional/tests/TramiteBlocoExternoInclusaoDeProcessoEmBlocoComHipoteseLegalNaoMapeadaTest.php, tests_sei41/funcional/tests/TramiteProcessoBlocoDeTramiteRegrasTest.php, tests_sei41/funcional/tests/TramiteProcessoComDocumentoRestritoHipotesePadraoTest.php, tests_sei41/funcional/tests/TramiteProcessoComDocumentoRestritoTest.php, tests_super/funcional/tests/FixtureCenarioBaseTestCase.php, tests_super/funcional/tests/TramiteBlocoExternoComProcessoNaoMapeadoRecusaTest.php, tests_super/funcional/tests/TramiteBlocoExternoInclusaoDeProcessoEmBlocoComHipoteseLegalNaoMapeadaTest.php, tests_super/funcional/tests/TramiteProcessoBlocoDeTramiteRegrasTest.php, tests_super/funcional/tests/TramiteProcessoComDocumentoRestritoHipotesePadraoTest.php, tests_super/funcional/tests/TramiteProcessoComDocumentoRestritoTest.php
=> test: corrige testes funcionais para BD oracle

src/rn/ExpedirProcedimentoRN.php
Ação de cancelamento de tramite validando de posssui tramite de fato e se esta vinculado a algum bloco
Closes #696
=> feat: ação de cancelamento de tramite.

tests_sei4/unitario/rn/ProcessoEletronicoRN/LitarEstruturasTest.php, tests_sei41/unitario/rn/ProcessoEletronicoRN/LitarEstruturasTest.php, tests_super/unitario/rn/ProcessoEletronicoRN/LitarEstruturasTest.php
Closes #717 
- teste unitario para listarEstruturas
=> test: test unitario

src/rn/ProcessoEletronicoRN.php, tests_sei4/unitario/rn/ProcessoEletronicoRN/BuscarEstruturasPorEstruturaPaiTest.php, tests_sei41/unitario/rn/ProcessoEletronicoRN/BuscarEstruturasPorEstruturaPaiTest.php, tests_super/unitario/rn/ProcessoEletronicoRN/BuscarEstruturasPorEstruturaPaiTest.php
Close #721 
- Teste unitário buscarEstruturaPorPai
=> test: Teste unitário

tests_sei4/unitario/rn/ProcessoEletronicoRN/ConsultarRepositoriosDeEstruturasTest.php, tests_sei41/unitario/rn/ProcessoEletronicoRN/ConsultarRepositoriosDeEstruturasTest.php, tests_super/unitario/rn/ProcessoEletronicoRN/ConsultarRepositoriosDeEstruturasTest.php
Close #715 
- Teste unitario consultar repositorios de estruturas
=> test: teste unitario

tests_sei41/funcional/tests/CenarioBaseTestCase.php
- Correção relativa à issue #764
=> test: correção de insert de unidades pen no cenariobasetest

tests_sei41/funcional/tests/CenarioBaseTestCase.php
=> test: remover warning cadastro unidades pen

tests_sei41/funcional/docker-compose.yml
=> test: remove msg de erro de configuração do tipo de banco de dados SIP

src/config/ConfiguracaoModPEN.php, src/rn/ExpedirProcedimentoRN.php, src/rn/ProcessoEletronicoRN.php, src/rn/ReceberProcedimentoRN.php, tests_sei41/funcional/tests/TramiteRecebimentoDocumentoAnexadoTest.php, tests_sei41/funcional/tests/TramiteRecebimentoDocumentoAvulsoTest.php, tests_sei41/funcional/tests/TramiteRecebimentoInteressadosDuplicadosTest.php, tests_sei41/funcional/tests/TramiteRecebimentoMultiplosComponentesDigitais.php, tests_sei41/funcional/tests/TramiteRecebimentoMultiplosComponentesDigitaisApenasPendentes.php
Testes atualizados/corrigidos
1. TramiteRecebimentoDocumentoAnexadoTest
2. TramiteRecebimentoDocumentoAvulsoTest
3. TramiteRecebimentoMultiplosComponentesDigitais
4. TramiteRecebimentoMultiplosComponentesDigitaisApenasPendentes
Closes #764
=> fix: correções dos testes automatizados que usam REST no teste

.github/workflows/phpcs.yml, phpcs.xml, src/rn/ProcessoEletronicoRN.php, src/rn/ReceberProcedimentoRN.php, tests_sei41/funcional/tests/CenarioBaseTestCase.php, tests_sei41/funcional/tests/RecebimentoRecusaJustificativaGrandeTest.php, tests_sei41/funcional/tests/TramiteProcessoComDocumentoRestritoTest.php, tests_sei41/funcional/tests/TramiteRecebimentoDocumentoAnexadoTest.php, tests_sei41/funcional/tests/TramiteRecebimentoDocumentoAvulsoTest.php, tests_sei41/funcional/tests/TramiteRecebimentoInteressadosDuplicadosTest.php, tests_sei41/funcional/tests/TramiteRecebimentoMultiplosComponentesDigitais.php, tests_sei41/funcional/tests/TramiteRecebimentoMultiplosComponentesDigitaisApenasPendentes.php
=> chore: phpcs e definição fixa de tomeout para testes automatizados com rest

tests_sei41/funcional/tests/FixtureCenarioBaseTestCase.php, tests_sei41/funcional/tests/TramiteProcessoComHistoricoTest.php
=> fix: compatibilizar testes funcionais com novas imagens sei 5.0.0

composer.json, src/rn/ExpedirProcedimentoRN.php, tests_sei5/funcional/composer.json
Número vai ser sempre inteiro ou com valor correto ou com 0
Closes #797
=> chore: corrige erro ao enviar campo número como string

Makefile, tests_sei41/funcional/assets/arquivos/test_files_index.txt, tests_sei41/funcional/docker-compose.yml, tests_sei41/funcional/env_mysql, tests_sei41/funcional/phpunit.xml, tests_sei41/funcional/tests/FixtureCenarioBaseTestCase.php, tests_sei41/funcional/tests/TramiteProcessoComHistoricoTest.php
=> 830 correcoes depermissoes e teste

src/rn/ProcessoEletronicoRN.php, tests_sei41/funcional/src/paginas/PaginaMapUnidades.php, tests_sei41/funcional/tests/MapeamentoDeUnidadesComUnidadeNaoVinculadaARepositorioSelcionadoTest.php, tests_super/funcional/src/paginas/PaginaMapUnidades.php, tests_super/funcional/tests/MapeamentoDeUnidadesComUnidadeNaoVinculadaARepositorioSelcionadoTest.php
=> feat: melhoria na mensagem para unidade selecionada não pertencente a repositorio de estruturas

src/rn/ProcessoEletronicoRN.php, tests_sei5/funcional/src/paginas/PaginaMapUnidades.php, tests_sei5/funcional/tests/MapeamentoDeUnidadesComUnidadeNaoVinculadaARepositorioSelcionadoTest.php
=> 852 melhoria mensagem sobre falha obtencao unidades externas

tests_sei5/funcional/tests/MapeamentoDeUnidadesComUnidadeNaoVinculadaARepositorioSelecionadoTest.php
Resolução de erro no nome de teste funcional
Close #876
=> 876 4 0 2 erro execucao testes automatizados

tests_sei41/funcional/src/paginas/PaginaAgendamentos.php, tests_sei41/funcional/tests/CancelamentoTramiteIndividualTest.php, tests_sei41/funcional/tests/CenarioBaseTestCase.php, tests_super/funcional/src/paginas/PaginaAgendamentos.php, tests_super/funcional/tests/CancelamentoTramiteIndividualTest.php, tests_super/funcional/tests/CenarioBaseTestCase.php
Teste realiza o cancelamento de tramites individuais
SEI 4.1.5 e SEI 4.0.12.15 tramita 3.8.3
closes #899
=> test: cancelamento tramite individual (#899)

tests_sei4/funcional/src/paginas/PaginaMapUnidades.php, tests_sei41/funcional/src/paginas/PaginaMapUnidades.php, tests_super/funcional/src/paginas/PaginaMapUnidades.php
A função "selecionarUnidadeComAlert" foi recolocada no arquivo PaginaMapUnidades.
=> inclusao_func_selecionarUnidadeComAlert

src/rn/ProcessarPendenciasRN.php, src/rn/ReceberProcedimentoRN.php
=> fix: corrige ultimo tramite apos API v4

src/rn/ReceberProcedimentoRN.php
=> fix: erro de encoding e erro de array ou objeto

src/rn/ExpedirProcedimentoRN.php
=> feat: envia versao assinada ao inves de impressa se houver p7s
